name: Check dead links

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 6'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install -g markdown-link-check
      - run: find . \( -name '*.md' -o -name '*.mdx' \) -exec markdown-link-check -c .github/workflows/config/link-check.json --progress {} \; 2>&1 | tee linkcheck.out
      - run: grep -q '[✖]\\|ERROR' ./linkcheck.out && exit 1 || true
